### ISSUE TITLE
[Google Forms Request]: FaceApp

### ISSUE THREAD

**Issue by jailbreak-bypass-forms** [hekatos/manifests#16] opened 2022-01-28 01:03 UTC
### Bypass requested from Google Forms
Response ID: 19
### App to request
 FaceApp
### App Store link
https://apps.apple.com/us/app/faceapp-face-photo-editor/id1180884341
### App version
10.1.2
### Jailbreak and iOS version
unc0ver , iOS 14.3
### Bypass tried
- A-Bypass
- Liberty Lite
- Hestia
- Shadow
- HideJB
- FlyJB x
### Which worked
N/A 
none can go through to edit page
### Checklist submission
- The app is missing from the table or bypasses are not working anymore
- I have checked through all open issues and none matched my app
- I have tried at least one bypass before submission.

**Comment by joshuah345** [comment] 2022-02-03 08:09
closing as duplicate of #5

**Closed as completed** 2022-02-03 08:09 UTC
Labels: duplicate
